# Generated by Django 2.2.13 on 2022-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210508_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuPiao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128, verbose_name='乳腺癌代码')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('volume', models.FloatField(verbose_name='成交量')),
                ('price_change', models.FloatField(verbose_name='价格变动')),
                ('p_change', models.FloatField(verbose_name='涨跌幅')),
                ('ma5', models.FloatField(verbose_name='5日均价')),
                ('ma10', models.FloatField(verbose_name='10日均价')),
                ('ma20', models.FloatField(verbose_name='20日均价')),
                ('v_ma5', models.FloatField(verbose_name='5日均量')),
                ('v_ma10', models.FloatField(verbose_name='10日均量')),
                ('v_ma20', models.FloatField(verbose_name='20日均量')),
                ('turnover', models.FloatField(verbose_name='换手率')),
            ],
            options={
                'verbose_name_plural': '乳腺癌',
            },
        ),
    ]
