# Generated by Django 2.2.13 on 2022-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gupiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.DateField(verbose_name='标题')),
                ('date', models.CharField(max_length=256, verbose_name='时间')),
                ('src', models.CharField(max_length=256, verbose_name='来源')),
            ],
        ),
    ]
