# Generated by Django 2.2.13 on 2022-03-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
