# Generated by Django 2.2.13 on 2022-03-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='hid',
        ),
        migrations.RemoveField(
            model_name='like',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='see',
            name='hid',
        ),
        migrations.RemoveField(
            model_name='see',
            name='uid',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='See',
        ),
    ]
