# Generated by Django 2.2.13 on 2022-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220309_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, verbose_name='名字')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('length', models.FloatField(verbose_name='长度')),
                ('width', models.FloatField(verbose_name='宽度')),
                ('cost', models.FloatField(verbose_name='花费时间')),
            ],
            options={
                'verbose_name_plural': '乳腺癌表',
            },
        ),
    ]
