# Generated by Django 2.2.13 on 2022-03-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_raod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
