# Generated by Django 2.2.13 on 2022-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('date', models.DateTimeField(verbose_name='时间')),
                ('img', models.CharField(max_length=256, verbose_name='图片')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
            ],
        ),
    ]
