# Generated by Django 2.2.13 on 2022-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='today_str',
            field=models.CharField(default='2022-03-11', max_length=256, verbose_name='什么时候爬取的'),
        ),
    ]
