# Generated by Django 2.2.13 on 2022-03-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_news_today_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuPiao',
        ),
        migrations.AlterModelOptions(
            name='raod',
            options={'verbose_name_plural': '乳腺癌信息表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '系统用户表'},
        ),
    ]
