# Generated by Django 2.2.13 on 2022-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220311_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perimeter_worst', models.FloatField(verbose_name='最差周长')),
                ('concave_points_worst', models.FloatField(verbose_name='最差凹点')),
                ('area_mean', models.FloatField(verbose_name='平均区域')),
                ('radius_worst', models.FloatField(verbose_name='最差半径')),
                ('area_worst', models.FloatField(verbose_name='最差区域')),
                ('perimeter_mean', models.FloatField(verbose_name='平均周长')),
                ('concave_points_mean', models.FloatField(verbose_name='平均凹点')),
                ('radius_mean', models.FloatField(verbose_name='平均半径')),
                ('concavity_mean', models.FloatField(verbose_name='平均凹度')),
                ('concavity_worst', models.FloatField(verbose_name='最差凹度')),
                ('compactness_worst', models.FloatField(verbose_name='最差紧密度')),
                ('area_se', models.FloatField(verbose_name='区域')),
                ('smoothness_worst', models.FloatField(verbose_name='最差平滑度')),
                ('radius_se', models.FloatField(verbose_name='半径')),
                ('texture_worst', models.FloatField(verbose_name='最差纹理')),
                ('diagnosis', models.IntegerField(verbose_name='是否为癌症')),
            ],
            options={
                'verbose_name_plural': '乳腺癌信息表',
            },
        ),
    ]
