# Generated by Django 2.2.13 on 2022-03-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_breast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Raod',
        ),
    ]
